Matthies/RubiChess

RubiChess/RubiChess.h
RubiChess/board.cpp
RubiChess/search.cpp
RubiChess/transposition.cpp

Removed most char and short variables by native integers. Move undo stuff now handled in a static stack.

Speed by simplification

---

RubiChess/RubiChess.h
RubiChess/board.cpp
RubiChess/main.cpp
RubiChess/search.cpp
RubiChess/transposition.cpp
RubiChess/utils.cpp

Speed improvements noticable: perft ~4% faster
1000 test games 10.0+0.1: 387 - 367 - 246  [0.510] 7 ELO

Optimizations

---

RubiChess/RubiChess.h
RubiChess/board.cpp
RubiChess/main.cpp
RubiChess/search.cpp

Should be faster and easier to maintain now.

Seperate root search

---

RubiChess/RubiChess.h
RubiChess/search.cpp
RubiChess/transposition.cpp

This seems very important and improves search a lot. Don't know why I didn't do that before.

Store the move in the TP even for beta cutoff.

---

RubiChess/RubiChess.h
RubiChess/board.cpp
RubiChess/search.cpp

STC:
Score of search4 vs master: 1113 - 985 - 922  [0.521] 3020
Elo difference: 14.73 +/- 10.32
SPRT: llr 2.2, lbound -2.2, ubound 2.2 - H1 was accepted
LTC:
Score of search6 vs master: 1221 - 1097 - 1299  [0.517] 3617
Elo difference: 11.92 +/- 9.06
SPRT: llr 2.2, lbound -2.2, ubound 2.2 - H1 was accepted

Searchextensions

---

RubiChess/RubiChess.h
RubiChess/board.cpp
RubiChess/main.cpp
RubiChess/search.cpp
RubiChess/tbprobe.cpp
RubiChess/utils.cpp

Better speed without functional change.

Preparestack

---

RubiChess/search.cpp
RubiChess/transposition.cpp
Tests/_temp/nmp.txt

More flexible nullmove search depth and condition. Big ELO gain.

Nmpverification

---

RubiChess/search.cpp

LTC[0,5]: 51,4% after 2266 games

Try (reverse) futility pruning before null move pruning.

---

Doku/Developers Log.txt
RubiChess/board.cpp
RubiChess/search.cpp

This fixes some Bugs and is ELO neutral. Tested 12335 games with +0.11 +/+ 4.59.

Experiments

---

RubiChess/RubiChess.h
RubiChess/board.cpp
RubiChess/eval.cpp
RubiChess/utils.cpp

Well, this started with introduction of king distance penalty which failed that way and ended in massive improvement of mobility evaluation.

Kingdistance

---

RubiChess/RubiChess.h
RubiChess/board.cpp
RubiChess/eval.cpp
RubiChess/search.cpp
RubiChess/utils.cpp

This reduces memory usage to ~15% and adds Keyboard commands to finish tuning soon/immediately.

Compresstexel

---

RubiChess/RubiChess.h
RubiChess/board.cpp
RubiChess/eval.cpp
RubiChess/main.cpp
RubiChess/search.cpp

This makes the evaluation faster (~4% searching from start position) without functional changes.

Evalcleanup

---

RubiChess/RubiChess.h
RubiChess/eval.cpp
RubiChess/search.cpp
RubiChess/utils.cpp

Implemented tuner for constant (not tapered) eval parameter which tempo is now.
It seems that tempo cannot be tuned as the tuned value was > 50 which fails badly in test. New values of 20 seems to do well. LTC is running, maybe it can even be lowered.
...
Tempo 12 did worse so 20 may be good.

Implemented simple evaluation after null move.

---

RubiChess/RubiChess.h
RubiChess/board.cpp
RubiChess/search.cpp
Tests/_temp/cm.txt

Reintroduce counter move as a third preferred quiet move. With this even resetting killers for child nodes seems to work.

Countermove

---

RubiChess/RubiChess.h
RubiChess/eval.cpp

This fixes #159 and may even win some few elo.

Connectedpawnfix

---

RubiChess/RubiChess.h
RubiChess/board.cpp
RubiChess/search.cpp

Cuckoo table implementation failed, so commit the simplification of repetition detection which seems good enough for some few Elo (+4,8  after 7600 STC games).

Repetition

---

src/RubiChess.h
src/main.cpp
src/uci.cpp

Should fix the issues AGE reported.

Some fixes for OpenBench.

---

src/RubiChess.h
src/eval.cpp

... and disabled / not working minor outpost.

Evalspeedup

---

src/board.cpp

Extends moveGivesCheck to discovered checks.
STC:
ELO   | 7.35 +- 5.01 (95%)
LLR   | 3.06 (-2.94, 2.94) [0.00, 5.00]
Games | N: 8750 W: 2168 L: 1983 D: 4599
LTC:
ELO   | 3.41 +- 2.71 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 5.00]
Games | N: 23650 W: 4549 L: 4317 D: 14784

Give check

---

src/Makefile
src/RubiChess.h
src/board.cpp
src/search.cpp

I did a lot of tests and it seems that this is not regressing and even fixes some bugs in ponder mode. Hope that with the searchguard thread removed now the test results at OpenBench will get more stable.

Removesearchguard

---

src/RubiChess.h
src/board.cpp

No more assertions running this with 8bit hash signature for two hours so it seems to fix #200

Epillegalfix

---

src/RubiChess.h
src/board.cpp
src/main.cpp
src/search.cpp
src/tbprobe.cpp
src/utils.cpp

STC:
ELO   | 4.14 +- 3.15 (95%)
LLR   | 2.95 (-2.94, 2.94) [0.00, 4.00]
Games | N: 20752 W: 4732 L: 4485 D: 11535
LTC:
ELO   | 7.59 +- 4.29 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 4.00]
Games | N: 8236 W: 1439 L: 1259 D: 5538

Technical - faster move generation

---

src/RubiChess.h
src/eval.cpp
src/transposition.cpp

Idea by Ed Schröder. Thanks!
STC:
ELO   | 7.74 +- 5.19 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 7724 W: 1822 L: 1650 D: 4252
LTC:
ELO   | 4.27 +- 3.22 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 15056 W: 2626 L: 2441 D: 9989

Pawnperfile

---

src/RubiChess.h
src/board.cpp
src/eval.cpp
src/main.cpp
src/utils.cpp

This exposes all the evaluation parameters to UCI options.
Enabled by EVALOPTIONS define.

Evaloptions

---

src/Makefile
src/Makefile.clang
src/RubiChess.h
src/board.cpp
src/eval.cpp
src/main.cpp
src/utils.cpp

This introduces BMI2/PEXT binary.

Pextsimple

---

src/RubiChess.h
src/search.cpp

This should finally fix issue #197

Matescores

---

src/search.cpp
src/tbprobe.cpp

STC:
ELO   | 1.36 +- 2.59 (95%)
LLR   | 2.98 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 28128 W: 5798 L: 5688 D: 16642
LTC:
ELO   | 1.27 +- 2.17 (95%)
LLR   | 2.96 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 29600 W: 4504 L: 4396 D: 20700

Aspiration

---

src/RubiChess.h
src/search.cpp

Cut unproven pv when failing low or high.

---

src/RubiChess.h
src/main.cpp
src/search.cpp

…of last search. Useful to detect bugs in position reset.
New benches:
2524532 (NNUE)
2662739 (Classic eval)

Benchmode uses follow up positions now by using best and pondermove

---

src/RubiChess.h

Fixes compilation for Mac OS and (hopefully) doesn't break anything for Windows and Linux.

Intrinheader

---

src/RubiChess.h

ELO   | 25.57 +- 2.34 (95%)
CONF  | 60.0+0.60s Threads=1 Hash=64MB
GAMES | N: 20000 W: 3122 L: 1653 D: 15225

New network 555efa676e.

---

src/RubiChess.h

STC:
ELO   | 18.95 +- 7.62 (95%)
GAMES | N: 2368 W: 417 L: 288 D: 1663
LTC:
ELO   | 14.02 +- 5.49 (95%)
GAMES | N: 3000 W: 355 L: 234 D: 2411

New network 49832fc04f

---

src/Makefile
src/RubiChess.h
src/cputest.cpp
src/utils.cpp

Fix includes intrin, cpuid for Windows.

---

src/RubiChess.h

STC:
ELO   | 5.42 +- 3.65 (95%)
GAMES | N: 9872 W: 1480 L: 1326 D: 7066
LTC:
ELO   | 3.92 +- 2.58 (95%)
GAMES | N: 12688 W: 1233 L: 1090 D: 10365

New network 26119c6435.

---

src/RubiChess.h

LTC1 (training) against master:
ELO   | 4.38 +- 3.47 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 18488 W: 4570 L: 4337 D: 9581
LTC2 (rescaling) against trained network:
ELO   | 5.75 +- 4.33 (95%)
GAMES | N: 12088 W: 3066 L: 2866 D: 6156

New network nn-d585174582-20220214.nnue

---

src/RubiChess.h

Best trained net against master:
STC:
ELO   | 5.79 +- 3.84 (95%)
GAMES | N: 9176 W: 1421 L: 1268 D: 6487
LTC:
ELO   | 5.34 +- 4.06 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 13600 W: 3406 L: 3197 D: 6997
Rescaled net against best trained net:
STC:
ELO   | 6.57 +- 4.09 (95%)
GAMES | N: 7720 W: 1153 L: 1007 D: 5560
LTC:
ELO   | 22.17 +- 10.20 (95%)
GAMES | N: 2432 W: 739 L: 584 D: 1109

New network nn-d458c5999d-20220222.nnue

---

src/RubiChess.h
src/board.cpp
src/engine.cpp
src/learn.cpp
src/main.cpp
src/move.cpp
src/search.cpp

STC:
ELO   | 3.33 +- 2.66 (95%)
GAMES | N: 32672 W: 8329 L: 8016 D: 16327
LTC:
ELO   | 3.19 +- 2.54 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 34704 W: 8540 L: 8221 D: 17943

Positionstack

---

src/RubiChess.h
src/engine.cpp
src/main.cpp
src/search.cpp

Fixes "premature bestmove while pondering" problem and simplifies time management.

Pondertime

---

src/RubiChess.h

STC:
ELO   | 3.68 +- 2.96 (95%)
GAMES | N: 28872 W: 8032 L: 7726 D: 13114
LTC:
ELO   | 6.72 +- 4.89 (95%)
GAMES | N: 10080 W: 2723 L: 2528 D: 4829

Update to net nn-bc67e15665-20220523.nnue

---

src/RubiChess.h
src/engine.cpp
src/search.cpp

ELO   | 27.2 +/- 13.3 (90%)
SPRT  | 20.0+0.00s Threads=1 Hash=8MB
LLR   | 2.2 (-2.2, 2.2) [0.00, 4.00]
GAMES | N: 1293 W: 370 L: 269 D: 654
ELO   | 8.04 +- 5.48 (95%)
SPRT  | 40/10.0+0.00s Threads=1 Hash=8MB
GAMES | N: 7736 W: 2032 L: 1853 D: 3851
ELO   | 11.37 +- 6.86 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 5136 W: 1426 L: 1258 D: 2452
ELO   | 7.26 +- 5.06 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 8904 W: 2286 L: 2100 D: 4518

Nodesbasedtm - idea by Koi devs

---

src/search.cpp

Fix output condition for MultiPV.

---

src/tbcore.c

Red is the patch, blue is master.

Open TB files with random access flag. Fixes bad performance in Linux.

---

src/RubiChess.h

STC:
ELO   | 6.88 +- 4.97 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 10000 W: 2766 L: 2568 D: 4666
LTC:
ELO   | 8.12 +- 4.58 (95%)
GAMES | N: 11552 W: 3158 L: 2888 D: 5506

New default network nn-0cea604698-20230119.nnue

---

src/RubiChess.h
src/engine.cpp
src/search.cpp
src/utils.cpp

This replaces the hack for the "wrong nps at long time control and fast computer" problem in a more reasonable way and without losing display of very low (limited) nps.

Timescaling

---

src/RubiChess.h
src/engine.cpp
src/main.cpp
src/search.cpp

Some cleanup in engine methods.

Move lastbestmovescore to engine object.

---

src/RubiChess.h

STC:
ELO   | 7.04 +- 4.22 (95%)
GAMES | N: 13712 W: 3751 L: 3473 D: 6488
LTC:
ELO   | 7.39 +- 4.31 (95%)
GAMES | N: 12736 W: 3387 L: 3116 D: 6233

New default network nn-fdccaaabd3-20230314.nnue

---

src/search.cpp

STC V1-Master:
ELO   | 3.27 +- 2.51 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 3.00]
GAMES | N: 37576 W: 9818 L: 9464 D: 18294
LTC V1-Master:
ELO   | 4.55 +- 3.19 (95%)
GAMES | N: 23432 W: 6182 L: 5875 D: 11375
STC V2-V1:
ELO   | 2.67 +- 2.13 (95%)
GAMES | N: 52368 W: 13711 L: 13308 D: 25349
LTC V2-V1:
ELO   | 1.53 +- 1.08 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 3.00]
GAMES | N: 200880 W: 51292 L: 50407 D: 99181

Nohashmove

---

src/RubiChess.h
src/engine.cpp
src/nnue.cpp

Elo   | 1.93 +- 2.17 (95%)
Games | N: 47014 W: 11346 L: 11085 D: 24583
Penta | [36, 5101, 12992, 5322, 56]

Tuned network's last layer

---

src/Makefile

Improve compiling for Android and possibly other systems.

Androidcompile

---

src/RubiChess.h
src/engine.cpp
src/eval.cpp
src/search.cpp

Don't prepare thread's position object before go command for better time control at TCEC.
Some say, it was cheating before ;-)

Dontdelaygo2
