Matthies/RubiChess

RubiChess/RubiChess.h
RubiChess/main.cpp
RubiChess/search.cpp
Tests/_temp/lmr.txt

10+0.1:
Score of RubiChess-Bitboard-lmr3 vs RubiChess-Bitboard-ms: 460 - 347 - 376  [0.548] 1183
Elo difference: 33.29 +/- 16.38
SPRT: llr 2.22, lbound -2.2, ubound 2.2 - H1 was accepted
60+0.6:
Score of RubiChess-Bitboard-lmr3 vs RubiChess-Bitboard-ms: 395 - 297 - 487  [0.542] 1179
Elo difference: 28.95 +/- 15.20
SPRT: llr 2.21, lbound -2.2, ubound 2.2 - H1 was accepted

Nmporder and improved LMR

---

RubiChess/search.cpp
Tests/_temp/aw.txt

STC against aw1:
Score of RubiChess-Bitboard-aw3 vs RubiChess-Bitboard-aw1: 595 - 510 - 645  [0.524] 1750
Elo difference: 16.89 +/- 12.93
SPRT: llr 1.37, lbound -1.39, ubound 1.39
LTC against master:
Score of RubiChess-Bitboard-aw3 vs RubiChess-Bitboard-ms: 161 - 96 - 236  [0.566] 493
Elo difference: 46.08 +/- 22.16

Aspirationwindow

---

RubiChess/search.cpp

STC:
Score of RubiChess-Bitboard-sort1 vs RubiChess-Bitboard-MS: 638 - 551 - 717  [0.523] 1906
Elo difference: 15.87 +/- 12.31
SPRT: llr 1.41, lbound -1.39, ubound 1.39 - H1 was accepted
LTC:
Score of RubiChess-Bitboard-sort1 vs RubiChess-Bitboard-MS: 1379 - 1286 - 2413  [0.509] 5078
Elo difference: 6.36 +/- 6.91

Sort moves in QSearch.

---

RubiChess/board.cpp

STC[0,5]:
Score of RubiChess-se1 vs RubiChess-ms: 552 - 484 - 787  [0.519] 1823
Elo difference: 12.97 +/- 12.01
SPRT: llr 1.39, lbound -1.39, ubound 1.39 - H1 was accepted
LTC[0,5]:
Score of RubiChess-se1 vs RubiChess-ms: 1487 - 1397 - 3357  [0.507] 6241
Elo difference: 5.01 +/- 5.85

Leave out captures with neutral see in quiescence search.

---

RubiChess/search.cpp

STC 1th:
Score of RubiChess-bm3 vs RubiChess-ms: 1290 - 1236 - 1983  [0.506] 4509
Elo difference: 4.16 +/- 7.58
SPRT: llr 1.38, lbound -1.39, ubound 1.39
STC 4th:
+297,=541,-240), 52.6 %

Don't set bestmovescore if hashvalue fails low.

---

RubiChess/RubiChess.h
RubiChess/board.cpp
RubiChess/search.cpp

Score of RubiChess-qsp4b vs RubiChess-ms: 392 - 340 - 1085  [0.514] 1817
Elo difference: 9.95 +/- 10.13
SPRT: llr 1.39, lbound -1.39, ubound 1.39 - H1 was accepted

Qsearchprune

---

RubiChess/RubiChess.h
RubiChess/board.cpp
RubiChess/eval.cpp
RubiChess/main.cpp
RubiChess/search.cpp

STC[0,5]:
Score of RubiChess-il5 vs RubiChess-ms: 385 - 323 - 602  [0.524] 1310
Elo difference: 16.46 +/- 13.82
LTC[0,5]:
Score of RubiChess-il5 vs RubiChess-ms: 678 - 614 - 1601  [0.511] 2893
Elo difference: 7.69 +/- 8.45
SPRT: llr 1.39, lbound -1.39, ubound 1.39 - H1 was accepted

kingpin evaluation

---

RubiChess/RubiChess.h
RubiChess/board.cpp
RubiChess/eval.cpp

kpa2
STC[0,5]:
Score of RubiChess-kpa2 vs RubiChess-ms: 388 - 323 - 521  [0.526] 1232
Elo difference: 18.35 +/- 14.73
LTC[0,5]
Score of RubiChess-kpa2 vs RubiChess-ms: 161 - 114 - 354  [0.537] 629
Elo difference: 26.01 +/- 17.93
SPRT: llr 1.41, lbound -1.39, ubound 1.39 - H1 was accepted
Wow!!!

Kingsupportspasser

---

RubiChess/search.cpp

All three tests passed very fast. LTC[0,5]:
Score of RubiChess-cmp2 vs RubiChess-cms: 219 - 171 - 510  [0.527] 900
Elo difference: 18.55 +/- 14.92
SPRT: llr 1.39, lbound -1.39, ubound 1.39 - H1 was accepted
Also the Arasan20 test suite gets ~10 more hits with this patch. 
This is a VERY good one.

Badcmpruning

---

src/search.cpp

STC:
ELO   | 4.33 +- 3.45 (95%)
Games | N: 19318 W: 4929 L: 4688 D: 9701
LTC:
ELO   | 19.62 +- 8.46 (95%)
Games | N: 2428 W: 524 L: 387 D: 1517

pvs fix (Tt at pv)

---

src/search.cpp

STC:
ELO   | 9.38 +- 5.88 (95%)
Games | N: 6003 W: 1428 L: 1266 D: 3309
LTC:
ELO   | 5.68 +- 3.94 (95%)
LLR   | 3.02 (-2.94, 2.94) [0.00, 5.00]
Games | N: 10463 W: 1927 L: 1756 D: 6780

Searchparams

---

src/RubiChess.h
src/board.cpp
src/main.cpp

STC (Openbench):
ELO   | 23.91 +- 9.04 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 4.00]
Games | N: 2576 W: 673 L: 496 D: 1407
LTC:
(+112,=392,- 62), 54.4 %
VLTC:
Score of crs1 vs cms: 142 - 95 - 641  [0.527] 878
Elo difference: 18.6 +/- 11.9, LOS: 99.9 %, DrawRatio: 73.0 %
SPRT: llr 2.21 (100.4%), lbound -2.2, ubound 2.2 - H1 was accepted

Resetstats

---

src/search.cpp

STC:
ELO   | 4.19 +- 3.33 (95%)
Games | N: 19078 W: 4486 L: 4256 D: 10336
LTC:
ELO   | 3.29 +- 2.60 (95%)
LLR   | 3.05 (-2.94, 2.94) [0.00, 5.00]
Games | N: 24800 W: 4605 L: 4370 D: 15825
Testing eet.epd at 3 seconds: 61/100 vs 56/100
This also solves/improves the bad endgame positions mentioned in DeveloperLog.

Experiments

---

src/transposition.cpp

Now that the pawnhash entry is 64 bytes use alligned allocation.

Alligned pawn hash allocation.

---

src/main.cpp
src/search.cpp
src/tbprobe.cpp
src/utils.cpp

In C++ "struct" before declaring a struct variable is no longer needed and it's really strange to read if sometimes you use them and sometimes you don't. I cleaned this up and removed all struct keywords before variable declarations.

Remove unnecessary "struct" keywords

---

src/board.cpp
src/search.cpp

This helps deltapruning a lot (raises from 1,09% to  6,68%).
STC:
ELO   | 3.51 +- 2.75 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 4.00]
Games | N: 26416 W: 5823 L: 5556 D: 15037
LTC:
ELO   | 4.54 +- 3.11 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 4.00]
Games | N: 15454 W: 2603 L: 2401 D: 10450

smart getBestPossibleCapture

---

src/RubiChess.h
src/board.cpp
src/search.cpp

Tests with static extension threshold
20+0.2:
ELO   | 9.97 +- 5.72 (95%)
SPRT  | 20.0+0.2s Threads=1 Hash=16MB
LLR   | 3.00 (-2.94, 2.94) [0.00, 5.00]
Games | N: 5264 W: 1057 L: 906 D: 3301
60+0.6:
ELO   | 3.29 +- 2.60 (95%)
Games | N: 21304 W: 3426 L: 3224 D: 14654
Test with dynamic extension to avoid stuck search:
60+0.6:
ELO   | 3.42 +- 2.65 (95%)
LLR   | 3.03 (-2.94, 2.94) [0.00, 5.00]
Games | N: 20608 W: 3321 L: 3118 D: 14169

history extension

---

src/RubiChess.h
src/search.cpp

STC:
ELO   | 5.18 +- 3.90 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 13280 W: 3005 L: 2807 D: 7468
LTC:
ELO   | 3.74 +- 2.89 (95%)
Games | N: 17648 W: 2910 L: 2720 D: 12018

Lets see if this 'more reduction after fail high in root' works in Rubi.

---

src/RubiChess.h
src/eval.cpp

STC:
ELO   | 5.94 +- 4.36 (95%)
Games | N: 11056 W: 2605 L: 2416 D: 6035
LTC:
ELO   | 8.23 +- 4.95 (95%)
LLR   | 3.01 (-2.94, 2.94) [0.00, 5.00]
Games | N: 6416 W: 1166 L: 1014 D: 4236

More penalty for unopposed isolated pawns.

---

src/RubiChess.h
src/eval.cpp

STC:
ELO   | 6.07 +- 4.42 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 10880 W: 2598 L: 2408 D: 5874
LTC:
ELO   | 4.75 +- 3.51 (95%)
Games | N: 12864 W: 2289 L: 2113 D: 8462

More penalty for unopposed backward pawns.

---

src/RubiChess.h
src/eval.cpp

…even without direct attack.
STC:
ELO   | 3.80 +- 3.05 (95%)
Games | N: 22320 W: 5121 L: 4877 D: 12322
LTC:
ELO   | 5.61 +- 3.95 (95%)
Games | N: 10336 W: 1887 L: 1720 D: 6729

Give some bonus for sliders going against the opponents king area

---

src/RubiChess.h
src/eval.cpp

STC:
ELO   | 2.66 +- 2.08 (95%)
SPRT  | 15.0+0.15s Threads=1 Hash=8MB
LLR   | 3.00 (-2.94, 2.94) [0.00, 5.00]
Games | N: 43168 W: 8849 L: 8519 D: 25800
LTC:
ELO   | 2.17 +- 1.70 (95%)
Games | N: 50656 W: 8220 L: 7903 D: 34533
STC for FRC:
ELO   | 6.43 +- 4.57 (95%)
SPRT  | 15.0+0.15s Threads=1 Hash=8MB
LLR   | 3.07 (-2.94, 2.94) [0.00, 5.00]
Games | N: 10480 W: 2572 L: 2378 D: 5530

Nocastlepenalty

---

src/RubiChess.h
src/search.cpp

STC:
ELO   | 10.54 +- 5.63 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 4616 W: 800 L: 660 D: 3156
LTC:
ELO   | 7.36 +- 4.03 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 6328 W: 771 L: 637 D: 4920

Save to tt more often.

---

src/search.cpp

STC:
ELO   | 2.73 +- 2.18 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 30408 W: 4891 L: 4652 D: 20865
LTC:
ELO   | 5.59 +- 3.34 (95%)
LLR   | 2.94 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 8448 W: 927 L: 791 D: 6730

Hashmove - reduce reduction at PV nodes for all but the bad hash moves

---

src/search.cpp

STC:
ELO   | 1.99 +- 1.53 (95%)
GAMES | N: 59464 W: 9176 L: 8835 D: 41453
LTC:
ELO   | 2.96 +- 2.21 (95%)
GAMES | N: 19376 W: 2058 L: 1893 D: 15425

Hashmove2 - History bonus for quiet hash moves failing high

---

src/board.cpp
src/search.cpp

STC:
ELO   | 5.66 +- 3.48 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 4.00]
GAMES | N: 11240 W: 1745 L: 1562 D: 7933
LTC:
ELO   | 7.15 +- 3.85 (95%)
LLR   | 2.99 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 6024 W: 644 L: 520 D: 4860
SMP:
ELO   | 5.10 +- 3.54 (95%)
SPRT  | 5.0+0.05s Threads=8 Hash=64MB
LLR   | 2.95 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 9136 W: 1195 L: 1061 D: 6880

Tm - more aggressive time usage for x+y time control

---

src/search.cpp

STC:
ELO   | 5.17 +- 3.56 (95%)
GAMES | N: 10696 W: 1651 L: 1492 D: 7553
LTC:
ELO   | 4.44 +- 2.81 (95%)
GAMES | N: 10952 W: 1098 L: 958 D: 8896

Futility Pruning retuned

---

src/search.cpp

STC:
ELO   | 4.76 +- 3.36 (95%)
GAMES | N: 11608 W: 1729 L: 1570 D: 8309
LTC:
ELO   | 6.23 +- 3.47 (95%)
GAMES | N: 7360 W: 772 L: 640 D: 5948

LMR even for tactical moves (long time no test of this).

---

src/search.cpp

ELO   | 2.03 +- 3.13 (95%)
LLR   | 2.95 (-2.94, 2.94) [-5.00, 0.00]
GAMES | N: 12856 W: 1783 L: 1708 D: 9365

Simplify tthit in root

---

src/RubiChess.h

b1c33 vs. 6b0c3
STC:
ELO   | 10.40 +- 6.44 (95%)
GAMES | N: 5616 W: 1498 L: 1330 D: 2788
LTC:
ELO   | 3.24 +- 2.59 (95%)
GAMES | N: 33688 W: 8363 L: 8049 D: 17276
6b0c3 vs. d3b95
STC:
ELO   | 12.14 +- 7.16 (95%)
GAMES | N: 4752 W: 1331 L: 1165 D: 2256
LTC:
ELO   | 5.66 +- 4.27 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 12648 W: 3258 L: 3052 D: 6338

New net nn-b1c332ae1d-20220613.nnue

---

src/RubiChess.h

Step1 (e34b5 vs. master)
STC:
ELO   | 4.72 +- 3.73 (95%)
GAMES | N: 17208 W: 4579 L: 4345 D: 8284
LTC:
ELO   | 3.67 +- 2.96 (95%)
GAMES | N: 27152 W: 7116 L: 6829 D: 13207
Step2 (5e38b vs. e34b5)
STC:
ELO   | 6.00 +- 4.91 (95%)
LLR   | 2.95 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 9904 W: 2644 L: 2473 D: 4787
LTC:
ELO   | 8.22 +- 5.91 (95%)
LLR   | 2.95 (-2.94, 2.94) [-1.00, 4.00]
GAMES | N: 6768 W: 1808 L: 1648 D: 3312

New default network nn-5e38b8ddf1-20221228.nnue

---

src/search.cpp

Fix valgrind warning.
STC:
ELO   | 2.05 +- 3.35 (95%)
LLR   | 2.96 (-2.94, 2.94) [-3.00, 1.00]
GAMES | N: 21360 W: 5596 L: 5470 D: 10294
LTC:
ELO   | 1.85 +- 3.19 (95%)
LLR   | 2.98 (-2.94, 2.94) [-3.00, 1.00]
GAMES | N: 23144 W: 5967 L: 5844 D: 11333

Currentmovenum

---

src/search.cpp

Fixes issue #407
ELO   | 0.59 +- 2.31 (95%)
SPRT  | 5.0+0.05s Threads=8 Hash=64MB
LLR   | 2.95 (-2.94, 2.94) [-3.00, 1.00]
GAMES | N: 44417 W: 11455 L: 11380 D: 21582

Stophelper

---

src/RubiChess.h
src/board.cpp
src/search.cpp

STC:
Elo   | 1.32 +- 1.45 (95%)
Games | N: 108252 W: 26847 L: 26437 D: 54968
Penta | [395, 12072, 28822, 12402, 435]
LTC:
Elo   | 2.80 +- 2.86 (95%)
Games | N: 27300 W: 6683 L: 6463 D: 14154
Penta | [18, 2937, 7533, 3131, 31]

Limitcheckextension

---

src/RubiChess.h

Another tuning going the full 25000 iterations in OB with one manual correction.
```
STC:
Elo   | 5.59 +- 4.22 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 3.00]
Games | N: 12860 W: 3280 L: 3073 D: 6507
Penta | [42, 1429, 3309, 1580, 70]
LTC:
Elo   | 2.51 +- 2.64 (95%)
Games | N: 31998 W: 7848 L: 7617 D: 16533
Penta | [30, 3473, 8770, 3688, 38]
```

Spsa 25000

---

src/learn.cpp

Fix for accumulator cache init in gensfen.

Fix missing accumulator cache init in the sfenreader.

---

src/RubiChess.h
src/learn.cpp
src/search.cpp

This improves forward/backward ananysis and should "fix" bad time management at tournaments with big machines and long TC like TCEC where Rubi gets stuck on depth n+1 after reading depth n from TT.
```
Elo   | 1.42 +- 3.17 (95%)
LLR   | 2.95 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 22258 W: 5445 L: 5354 D: 11459
Penta | [24, 2351, 6287, 2444, 23]
http://chess.grantnet.us/test/36736/
```
Bench: 5450474

Don't return with TT move and score in root.

---

src/search.cpp

STC:
Elo   | 3.20 +- 2.99 (95%)
Games | N: 25602 W: 6453 L: 6217 D: 12932
Penta | [96, 2948, 6507, 3124, 126]
LTC:
Elo   | 8.36 +- 5.45 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 3.00]
Games | N: 7444 W: 1868 L: 1689 D: 3887
Penta | [2, 742, 2059, 913, 6]
Bench: 5134491

Store native depth in TT.
